Repository STAR-TIDES/kb, pull requests merged in 2021-06, with the labels that each got.

#26 Feature/issue 8
  docker-compose.yaml
  pylintrc
  star_tides/api/controllers/auth_controller.py
  star_tides/api/controllers/base_controller.py
  star_tides/api/controllers/test_auth_controller.py
  star_tides/api/routes/__init__.py
  star_tides/api/routes/auth_route.py
  star_tides/constants.py
  star_tides/core/actions/create_user_action.py
  star_tides/core/actions/login_user_action.py
  star_tides/requirements.txt
  star_tides/services/databases/__init__.py
  star_tides/services/databases/mongo/__init__.py
  star_tides/services/databases/mongo/models/__init__.py
  star_tides/services/databases/mongo/models/user_model.py
  star_tides/services/databases/mongo/schemas/__init__.py
  star_tides/services/databases/mongo/schemas/user_schema.py
  star_tides/services/interfaces/__init__.py
  star_tides/services/interfaces/user_interface.py
  star_tides/services/interfaces/utils/__init__.py
  star_tides/services/interfaces/utils/interface_decorator.py
  star_tides/services/mongo/models/user_model.py
  star_tides/tests/fixtures/basic_user.py
  star_tides/tests/utils.py
  star_tides/utils/__init__.py
  star_tides/utils/random_string.py
Labels: enhancement

#31 Updated requirements.txt to include specific version
  star_tides/requirements.txt
Labels: Requires Rebuild

#36 Feature/issue 21 login required
  star_tides/api/blueprint.py
  star_tides/api/controllers/base_controller.py
  star_tides/api/decorators/login_required.py
  star_tides/api/decorators/test_login_required.py
  star_tides/api/util/issue_jwt.py
Labels: enhancement

#37 Added refresh_token
  star_tides/api/controllers/auth_controller.py
  star_tides/api/util/issue_jwt.py
  star_tides/core/actions/login_user_action.py
Labels: enhancement

#42 Add Contact model (document) and associated models, etc. to codebase.
  star_tides/api/blueprint.py
  star_tides/services/databases/mongo/models/availability.py
  star_tides/services/databases/mongo/models/contact_model.py
  star_tides/services/databases/mongo/models/engagement_model.py
  star_tides/services/databases/mongo/models/location_model.py
  star_tides/services/databases/mongo/models/test_availability.py
Labels: Database Layer, enhancement
